page.wait_for_timeout(700)
expect(page.locator('#stage .card')).to_have_count(12)
snap('Focus: one story at a time')
card=page.locator('#stage .card[data-id="oner"]')
y=page.locator('#stage').evaluate('(e)=>e.scrollTop')
card.get_by_role('button',name='Save story',exact=True).click()
assert page.locator('#stage').evaluate('(e)=>e.scrollTop')==y
card.get_by_role('button',name='Add a note',exact=True).click()
note=card.get_by_role('textbox',name='Your note',exact=True)
note.fill('Try this camera move on Friday. My angle: rehearsal matters.')
note.press('ArrowDown');page.wait_for_timeout(300)
assert page.locator('#stage').evaluate('(e)=>e.scrollTop')==y
snap('One tap to jot a personal note')
page.reload();page.wait_for_timeout(450)
expect(page.locator('#stage .card[data-id="oner"] textarea')).to_have_value('Try this camera move on Friday. My angle: rehearsal matters.')
page.get_by_role('tab',name='Explore',exact=True).click();page.wait_for_timeout(450)
expect(page.locator('#stage .tile[data-id="oner"]')).to_contain_text('Has note')
snap('Explore: an open collection of topics')
page.locator('#stage .tile[data-id="grid"] h3').click();page.wait_for_timeout(450)
snap('Open a YouTube topic for context')
page.locator('#reader').get_by_role('button',name='Save story',exact=True).click()
page.locator('#reader').get_by_role('button',name='Close',exact=True).click()
b('Saved stories').click();page.wait_for_timeout(350)
expect(page.locator('#tray .tray-item')).to_have_count(2)
page.locator('#tray .tray-item').nth(1).get_by_role('button',name='Move up',exact=True).click()
assert page.locator('#tray .tray-item').first.get_attribute('data-id')=='grid'
snap('Saved topics with your notes and a simple order')
page.locator('#tray').get_by_role('button',name='Close',exact=True).click()
page.get_by_role('tab',name='Focus',exact=True).click()
card=page.locator('#stage .card[data-id="oner"]')
card.get_by_role('button',name='Less like this',exact=True).click()
b('Tune feed').click();page.wait_for_timeout(300)
snap('Inspect or undo local preferences')
page.locator('#tune [data-act="refresh"]').click();page.wait_for_timeout(350)
assert page.locator('#stage .card').first.get_attribute('data-id')!='oner'
page.keyboard.press('Escape')
snap('Feedback changes the next feed order')
b('Tune feed').click();page.locator('#tune [data-act="reset"]').click()
page.keyboard.press('Escape')
assert page.evaluate('window.__rundown.state.notes.oner')=='Try this camera move on Friday. My angle: rehearsal matters.'
assert len(page.evaluate('window.__rundown.state.saved'))==2
page.reload();page.wait_for_timeout(450)
assert page.evaluate('window.__rundown.state.saved[0]')=='grid'
page.set_viewport_size({'width':390,'height':844})
page.wait_for_timeout(400)
assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
snap('Phone: Focus feed')
page.get_by_role('tab',name='Explore',exact=True).click();page.wait_for_timeout(450)
snap('Phone: Explore feed')
page.locator('#stage .tile[data-id="serve"] h3').click();page.wait_for_timeout(400)
snap('Phone: TikTok story preview')
page.locator('#reader').get_by_role('button',name='Close',exact=True).click()
page.locator('#stage .tile[data-id="fans"] h3').click();page.wait_for_timeout(400)
snap('Phone: Reddit conversation')
assert not errors,errors
assert all(u.startswith('http://127.0.0.1:3187/') or u.startswith('data:') for u in requests),requests
print('PARENT ACCEPTANCE PASSED',flush=True)
